server:
  port: 8081
spring:
  application:
    name: product
  datasource:
    username: root
    password: 975109ljm
    url: jdbc:mysql://127.0.0.1:3306/cloud
mybatis:
  type-aliases-package: com.hq.product.pojo
  mapper-locations: classpath:mapper/*.xml
